"""Generate reports from local data"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

START, END = "<!-- METRICS:START -->", "<!-- METRICS:END -->"


def fmt(v, suffix=""):
    return "—" if v is None else f"{v}{suffix}"


def metrics_markdown(pm: dict, rm: dict) -> str:
    lines = ["_Auto-generated by `scripts/generate_reports.py` from local data — never hand-edited._", ""]
    lines.append("**User research**  ")
    if rm["status"] != "ok":
        lines.append("User research collection in progress. (No survey responses imported into this repo; research done "
                     "outside the app is author-reported — see the User Research section.)")
    else:
        lines += [f"- Survey respondents: **{rm['respondent_count']}**",
                  f"- Median weekly search time: **{fmt(rm['median_weekly_search_hours'], ' h')}**",
                  f"- Mean time per application: **{fmt(rm['mean_minutes_per_application'], ' min')}**"]
        if rm["top_pain_points"]:
            lines.append("- Top pain points: " + ", ".join(f"{p['item']} ({p['count']})" for p in rm["top_pain_points"][:3]))
        if rm["most_used_tools"]:
            lines.append("- Most-used tools: " + ", ".join(f"{p['item']} ({p['count']})" for p in rm["most_used_tools"][:3]))
    lines += ["", "**Product usage & time saved (measured, local instance)**", "",
              "| Metric | Value |", "|---|---|",
              f"| Real users | {pm['real_users']} |", f"| Jobs analyzed | {pm['jobs_analyzed']} |",
              f"| Applications started / completed | {pm['applications_started']} / {pm['applications_completed']} |",
              f"| Median job-evaluation time | {fmt(pm['median_job_evaluation_time_minutes'], ' min')} |",
              f"| Median application-prep time | {fmt(pm['median_application_preparation_time_minutes'], ' min')} |",
              f"| Time-saved observations (self-reported baseline) | {pm['observations_with_baseline']} (claim threshold: {pm['claim_threshold']}) |"]
    if pm["claimable"]:
        lines += [f"| Median baseline → assisted | {fmt(pm['median_baseline_minutes'], ' min')} → {fmt(pm['median_assisted_minutes'], ' min')} |",
                  f"| Median time reduction | {fmt(pm['median_time_reduction_pct'], '%')} |"]
    else:
        lines.append("| Median time reduction | Not claimable yet — not enough observations |")
    lines.append(f"| Resume-suggestion acceptance rate | {fmt(pm['resume_suggestion_acceptance_rate'])} |")
    return "\n".join(lines)


def resume_bullets(pm: dict, rm: dict) -> str:
    out = ["# Resume bullets", "",
           "> Generated by `scripts/generate_reports.py`. Only claims that are true *today* are included; extra bullets",
           "> appear automatically once real data supports them. Do not add numbers by hand.", "",
           "## CoopCompass: AI Co-op Search Assistant | React, TypeScript, FastAPI, SQLite, Gemini, sentence-transformers", "",
           "- Built an AI-assisted job-search platform that ranks co-op opportunities using explainable skill, experience, role, "
           "education, location, and preference matching rather than opaque LLM-generated scores.",
           "- Developed an evidence-grounded resume assistant using Gemini that identifies JD gaps and generates application "
           "suggestions exclusively from verified resume experience, with a deterministic check that rejects invented technologies or numbers.",
           "- Instrumented the complete job-search funnel from discovery → analysis → application → interview, enabling measurement of "
           "application preparation time, conversion, recommendation quality, and eventual time savings."]
    if rm["status"] == "ok" and rm["respondent_count"] > 0:
        extra = f"- Designed and ran a student job-search survey ({rm['respondent_count']} responses)"
        if rm["median_weekly_search_hours"] is not None:
            extra += f"; respondents reported a median of {rm['median_weekly_search_hours']} hours/week searching"
        if rm["top_pain_points"]:
            extra += f"; top pain point: {rm['top_pain_points'][0]['item']} ({rm['top_pain_points'][0]['count']} mentions)"
        out.append(extra + ".")
    if pm["claimable"] and pm["median_time_reduction_pct"] is not None:
        out.append(f"- Measured a median {pm['median_time_reduction_pct']}% reduction in self-reported application effort "
                   f"(median {pm['median_baseline_minutes']} → {pm['median_assisted_minutes']} min, n={pm['observations_with_baseline']} applications).")
    out += ["", "## Not yet claimable (needs real data)", ""]
    if rm["status"] != "ok":
        out.append("- Survey / interview findings: none imported or recorded yet. Do not cite participant counts.")
    if not pm["claimable"]:
        out.append(f"- Time saved: {pm['observations_with_baseline']} of {pm['claim_threshold']} required observations. Do not cite time savings.")
    if pm["applications_completed"] == 0:
        out.append("- Application outcomes (interview / offer rates): no completed applications recorded.")
    return "\n".join(out) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", help="SQLite file (default: the app's real database)")
    args = ap.parse_args()
    if args.db:
        os.environ["DATABASE_URL"] = f"sqlite:///{Path(args.db).resolve().as_posix()}"

    from backend.app.db import get_session, init_db
    from backend.app.services import metrics

    init_db()
    s = get_session()
    pm = metrics.compute_product_metrics(s)
    rm = metrics.compute_research_metrics(metrics.research_rows(s))
    (ROOT / "reports").mkdir(exist_ok=True)
    (ROOT / "reports" / "product_metrics.json").write_text(json.dumps(pm, indent=2), encoding="utf-8")
    (ROOT / "reports" / "research_metrics.json").write_text(json.dumps(rm, indent=2), encoding="utf-8")

    readme = ROOT / "README.md"
    if readme.exists():
        text = readme.read_text(encoding="utf-8")
        if START in text and END in text:
            block = f"{START}\n{metrics_markdown(pm, rm)}\n{END}"
            text = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
            readme.write_text(text, encoding="utf-8")
    (ROOT / "docs" / "resume-bullets.md").write_text(resume_bullets(pm, rm), encoding="utf-8")
    print("Wrote reports/product_metrics.json, reports/research_metrics.json, docs/resume-bullets.md (+ README metrics block)")


if __name__ == "__main__":
    main()
